In [1]:
x = 3
println(x, " ", typeof(x))

3 Int64


In [2]:
α = 12.0
println("α = ", α)
f(x) = 2x^2 + 3x + 1
println(f(3))

α = 12.0
28


In [3]:
g(x) = f(x) - (2x + 1)*(x+1)
g(3.5)

0.0

In [4]:
h = f
h(3)

28

# String Interpolation

In [5]:
name = "Satish"
greeting = "Hello, $name"
println(greeting)

Hello, Satish


# Numeric Types

In [10]:
a = round(Int, 1e16)

10000000000000000

In [7]:
typeof(2)

Int64

In [9]:
a = Int8(10)
b = Int8(20)
a + b

30

In [12]:
x = 2^53 + 1
Float64(x) == x

false

In [13]:
big(10)

10

In [14]:
10^5

100000

In [15]:
10^19

-8446744073709551616

In [16]:
big(3)^2000

1747871251722651609659974619164660570529062487435188517811888011810686266227275489291486469864681111075608950696145276588771368435875508647514414202093638481872912380089977179381529628478320523519319142681504424059410890214500500647813935818925701905402605484098137956979368551025825239411318643997916523677044769662628646406540335627975329619264245079750470862462474091105444437355302146151475348090755330153269067933091699479889089824650841795567478606396975664557143737657027080403239977757865296846740093712377915770536094223688049108023244139183027962484411078464439516845227961935221269814753416782576455507316073751985374046064592546796043150737808314501684679758056905948759246368644416151863138085276603595816410945157599742077617618911601185155602080771746785959359879490191933389965271275403127925432247963269675912646103156343954375442792688936047041533537523137941310690833949767764290081333900380310406154723157882112449991673819054110440001

In [17]:
typemax(Int)

9223372036854775807

In [18]:
Base.checked_add(typemax(Int), 1)

LoadError: LoadError: OverflowError()
while loading In[18], in expression starting on line 1

In [19]:
z = 1 + 2im
z * 2

2 + 4im

In [21]:
1//3 < 1/3

false

In [22]:
1//3 * 9

3//1

In [23]:
1//4 == 0.25

true

In [24]:
1//3 * 2.5

0.8333333333333333

In [25]:
y = 1//3 + 3//4

13//12

In [26]:
println(y.num, ", ", y.den)

13, 12


# Arrays

In [27]:
x = [1. 2 3 4 5]

1x5 Array{Float64,2}:
 1.0  2.0  3.0  4.0  5.0

In [28]:
y = [1, 'a', "Satish"]
typeof(y)
println(y)
push!(y, 100)
println(y)

Any[1,'a',"Satish"]
Any[1,'a',"Satish",100]


In [29]:
typeof(1:10:1000)

StepRange{Int64,Int64}

In [30]:
?push!

search: push! pushdisplay



```rst
..  push!(collection, items...) -> collection

Insert one or more ``items`` at the end of ``collection``.

.. doctest::

  julia> push!([1, 2, 3], 4, 5, 6)
  6-element Array{Int64,1}:
   1
   2
   3
   4
   5
   6

Use :func:`append!` to add all the elements of another collection to
``collection``.
The result of the preceding example is equivalent to
``append!([1, 2, 3], [4, 5, 6])``.
```


In [31]:
methods(push!)

# 15 methods for generic function "push!":
push!(a::Array{Any,1}, item::ANY) at array.jl:440
push!{T}(a::Array{T,1}, item) at array.jl:433
push!(B::BitArray{1}, item) at bitarray.jl:455
push!(s::IntSet, n::Integer) at intset.jl:51
push!(t::Associative{K,V}, p::Pair{A,B}) at dict.jl:294
push!(t::Associative{K,V}, p::Pair{A,B}, q::Pair{A,B}) at dict.jl:295
push!(t::Associative{K,V}, p::Pair{A,B}, q::Pair{A,B}, r::Pair{A,B}...) at dict.jl:296
push!(s::Set{T}, x) at set.jl:29
push!(::Base.EnvHash, k::AbstractString, v) at env.jl:94
push!(c::CompositeException, ex) at task.jl:42
push!(md::Base.Markdown.MD, x) at markdown/parse/parse.jl:23
push!(t::Associative{K,V}, key, v) at deprecated.jl:49
push!(A) at deprecated.jl:439
push!(A, a, b) at abstractarray.jl:1390
push!(A, a, b, c...) at abstractarray.jl:1391

In [32]:
@which push!(y, 200)

push!(a::Array{Any,1}, item::ANY) at array.jl:440

In [33]:
2 == 3

false

In [34]:
[1, 2] == [1, 2.0]

true

In [35]:
a = [1 2; 3 4]
b = [1 2 3; 4 5 6]
a

2x2 Array{Int64,2}:
 1  2
 3  4

In [36]:
b

2x3 Array{Int64,2}:
 1  2  3
 4  5  6

In [37]:
a * b

2x3 Array{Int64,2}:
  9  12  15
 19  26  33

In [38]:
methods(cross)

# 1 method for generic function "cross":
cross(a::AbstractArray{T,1}, b::AbstractArray{T,1}) at linalg/generic.jl:37

In [39]:
+(2, 5)

7

In [40]:
v = [1, 2]
M = [2 1; 3 4]
M * v

2-element Array{Int64,1}:
  4
 11